# Generated by Django 4.1.7 on 2023-04-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subscribe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('user', 'subscribedTo')},
        ),
    ]
